"""
Step 5: Silent Failure Test (Experiment 4)
FedGAN Failure Analysis - Anish Bharadwaj

The core experiment of the paper.

Setup:
- Train a simple CNN classifier on SYNTHETIC data generated by each FedGAN
- Test that classifier on REAL PathMNIST test images
- Compare accuracy across IID, Non-IID, Noisy Client generators
- Also train a reference classifier on REAL data as the upper bound

The gap between real-data accuracy and synthetic-data accuracy
= the silent failure gap.

A high FID means poor image quality — visible to metrics.
A high silent failure gap means clinical incorrectness — invisible to FID.
This is the key finding of the paper.
"""

import os
import json
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from torchvision import transforms
from medmnist import PathMNIST
from dcgan import Generator, LATENT_DIM

# Config
DATA_DIR        = "./data"
CKPT_DIR        = "./checkpoints"
LOG_DIR         = "./logs"
N_SYNTHETIC     = 10000   # synthetic images to generate per experiment
BATCH_SIZE      = 128
CLASSIFIER_LR   = 0.001
CLASSIFIER_EPOCHS = 15
NUM_CLASSES     = 9
DEVICE          = torch.device("cuda" if torch.cuda.is_available() else "cpu")

EXPERIMENTS = {
    "IID Baseline" : "generator_iid_final.pt",
    "Non-IID"      : "generator_non_iid_final.pt",
    "Noisy Client" : "generator_noisy_client_final.pt",
}

print(f"Device: {DEVICE}\n")


# Simple CNN Classifier
class TissueClassifier(nn.Module):
    """
    Lightweight CNN for 9-class tissue classification.
    Intentionally simple — the point is not classifier performance,
    it is the gap between training on real vs synthetic data.
    Same architecture used for every experiment for fair comparison.
    """
    def __init__(self, num_classes=NUM_CLASSES):
        super().__init__()
        self.features = nn.Sequential(
            # Block 1
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),           # 28 → 14

            # Block 2
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),           # 14 → 7

            # Block 3
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.AdaptiveAvgPool2d((3, 3)),   # 7 → 3
        )
        self.classifier = nn.Sequential(
            nn.Dropout(0.4),
            nn.Linear(128 * 3 * 3, 256),
            nn.ReLU(inplace=True),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), -1)
        return self.classifier(x)


# Generate Synthetic Dataset
@torch.no_grad()
def generate_synthetic_data(generator, n_samples=N_SYNTHETIC):
    """
    Generate synthetic images from a trained generator.
    Labels are assigned by round-robin across 9 classes.

    Important note for paper: the generator is unconditional —
    it has no explicit class label control. Labels are assigned
    uniformly as a best-case assumption. In reality the generator
    may have collapsed certain classes entirely, making the
    assigned labels incorrect — this is part of the silent failure.
    """
    generator.eval()
    all_imgs = []
    generated = 0

    while generated < n_samples:
        bs   = min(BATCH_SIZE, n_samples - generated)
        z    = torch.randn(bs, LATENT_DIM, 1, 1).to(DEVICE)
        imgs = generator(z)
        all_imgs.append(imgs.cpu())
        generated += bs

    imgs = torch.cat(all_imgs, dim=0)[:n_samples]
    imgs = (imgs + 1) / 2   # [-1,1] → [0,1]
    imgs = imgs.clamp(0, 1)

    # Uniform label assignment — best-case scenario for synthetic data
    labels = torch.tensor([i % NUM_CLASSES for i in range(n_samples)],
                          dtype=torch.long)

    return imgs, labels


# Real Data Loaders
def get_real_loaders():
    transform = transforms.Compose([
        transforms.ToTensor(),
        # No normalisation here — classifier expects [0,1]
        # Synthetic data is also in [0,1] for fair comparison
    ])
    train_ds = PathMNIST(split="train", transform=transform,
                         download=False, root=DATA_DIR)
    test_ds  = PathMNIST(split="test",  transform=transform,
                         download=False, root=DATA_DIR)

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE,
                              shuffle=True,  num_workers=0)
    test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE,
                              shuffle=False, num_workers=0)
    return train_loader, test_loader


# Train Classifier
def train_classifier(train_loader, tag=""):
    model     = TissueClassifier().to(DEVICE)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=CLASSIFIER_LR)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.5)

    for epoch in range(CLASSIFIER_EPOCHS):
        model.train()
        total_loss = 0
        for imgs, labels in train_loader:
            imgs   = imgs.to(DEVICE)
            labels = labels.to(DEVICE).squeeze().long()
            optimizer.zero_grad()
            out  = model(imgs)
            loss = criterion(out, labels)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        scheduler.step()

        if (epoch + 1) % 5 == 0:
            avg = total_loss / len(train_loader)
            print(f"    Epoch {epoch+1:2d}/{CLASSIFIER_EPOCHS} | Loss: {avg:.4f}")

    return model


# Evaluate Classifier
@torch.no_grad()
def evaluate(model, test_loader):
    """Evaluate on REAL test data — same test set for every classifier."""
    model.eval()
    correct, total = 0, 0
    per_class_correct = torch.zeros(NUM_CLASSES)
    per_class_total   = torch.zeros(NUM_CLASSES)

    for imgs, labels in test_loader:
        imgs   = imgs.to(DEVICE)
        labels = labels.squeeze().long()
        preds  = model(imgs.to(DEVICE)).argmax(dim=1).cpu()
        correct += (preds == labels).sum().item()
        total   += labels.size(0)
        for c in range(NUM_CLASSES):
            mask = labels == c
            per_class_correct[c] += (preds[mask] == labels[mask]).sum()
            per_class_total[c]   += mask.sum()

    overall_acc = correct / total * 100
    per_class_acc = (per_class_correct / per_class_total.clamp(min=1) * 100).tolist()
    return overall_acc, per_class_acc


# Main
if __name__ == "__main__":
    CLASS_NAMES = ['adipose', 'background', 'debris', 'lymphocytes',
                   'mucus', 'smooth muscle', 'normal colon', 'cancer stroma',
                   'adenocarcinoma']

    _, test_loader = get_real_loaders()
    results = {}

    # Reference: classifier trained on REAL data
    print("="*55)
    print(" REFERENCE: Training classifier on REAL data")
    print("="*55)
    real_train_loader, _ = get_real_loaders()
    ref_model   = train_classifier(real_train_loader, tag="real")
    ref_acc, ref_per_class = evaluate(ref_model, test_loader)
    results["Real Data (Reference)"] = {
        "overall_accuracy": round(ref_acc, 2),
        "per_class_accuracy": [round(x, 2) for x in ref_per_class]
    }
    print(f"  → Overall Accuracy: {ref_acc:.2f}%\n")

    # Synthetic classifiers
    for exp_name, ckpt_file in EXPERIMENTS.items():
        ckpt_path = os.path.join(CKPT_DIR, ckpt_file)
        if not os.path.exists(ckpt_path):
            print(f"MISSING: {ckpt_path} — skipping")
            continue

        print("="*55)
        print(f" {exp_name}: Training classifier on SYNTHETIC data")
        print("="*55)

        # Load generator
        G = Generator().to(DEVICE)
        G.load_state_dict(torch.load(ckpt_path, map_location=DEVICE))

        # Generate synthetic training data
        print(f"  Generating {N_SYNTHETIC} synthetic images...")
        syn_imgs, syn_labels = generate_synthetic_data(G, N_SYNTHETIC)
        syn_dataset = TensorDataset(syn_imgs, syn_labels)
        syn_loader  = DataLoader(syn_dataset, batch_size=BATCH_SIZE,
                                 shuffle=True, num_workers=0)

        # Train classifier on synthetic data
        model = train_classifier(syn_loader, tag=exp_name)

        # Evaluate on REAL test data
        acc, per_class = evaluate(model, test_loader)
        results[exp_name] = {
            "overall_accuracy": round(acc, 2),
            "per_class_accuracy": [round(x, 2) for x in per_class]
        }
        print(f"  → Overall Accuracy on Real Test Set: {acc:.2f}%\n")

    #Summary Table
    print("="*55)
    print(" SILENT FAILURE RESULTS")
    print("="*55)
    ref_acc_val = results["Real Data (Reference)"]["overall_accuracy"]
    print(f"  {'Experiment':<28} {'Accuracy':>10} {'Gap vs Real':>12}")
    print(f"  {'-'*52}")
    for name, data in results.items():
        acc = data["overall_accuracy"]
        gap = acc - ref_acc_val
        gap_str = f"{gap:+.2f}%" if name != "Real Data (Reference)" else "—"
        print(f"  {name:<28} {acc:>9.2f}% {gap_str:>12}")
    print("="*55)

    print("\nPer-class accuracy breakdown:")
    print(f"  {'Class':<25}", end="")
    for name in results:
        short = name.split()[0][:8]
        print(f"  {short:>10}", end="")
    print()
    for i, cls in enumerate(CLASS_NAMES):
        print(f"  {cls:<25}", end="")
        for name in results:
            print(f"  {results[name]['per_class_accuracy'][i]:>9.1f}%", end="")
        print()

    # Save
    log_path = os.path.join(LOG_DIR, "silent_failure_results.json")
    with open(log_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nResults saved → {log_path}")
    print("\nExperiment 4 complete.")
